all:
	make all -C bfs
#	make all -C sssp
#	make all -C cc
	make all -C pagerank
	make all -C parallel_search
clean:
	make clean -C bfs
#	make clean -C sssp
#	make clean -C cc
	make clean -C pagerank
	make clean -C parallel_search
